[package]
name = "integration-tests-bindings"
version = "0.1.0"
edition = "2018"

[dependencies]
dart-api-dl = { package="xayn-dart-api-dl", version="0.3.0" }
once_cell = "1.8.0"
thiserror = "1.0.30"

[lib]
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cbindgen = "=0.20.0"
