[package]
name = "xayn-dart-api-dl"
version = "0.3.0+2.0.0"
edition = "2018"
license = "Apache-2.0"

[dependencies]
dart-api-dl-sys = { package = "xayn-dart-api-dl-sys", version = "0.3.0" }
once_cell = "1.9.0"
static_assertions = "1.1.0"
thiserror = "1.0.30"
